export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',

  ssr: true,

  devtools: { enabled: false },
  modules: [
    '@nuxtjs/tailwindcss',
    'nuxt-gtag',
  ],

  gtag: {
    id: 'G-XWL8VTL6T8'
  },

 nitro: {
  prerender: {
    crawlLinks: true,
    failOnError: false,
    routes: [
      '/features/apis'
    ]
  },

  compressPublicAssets: true,

  routeRules: {
    '/_nuxt/**': {
      headers: {
        'Cache-Control': 'public, max-age=31536000, immutable'
      }
    },

    '/**': {
      swr: 3600,
      headers: {
        'Cache-Control': 'public, max-age=3600'
      }
    }
  }
},



  app: {
    head: {
      htmlAttrs: {
        lang: 'en'
      },

      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        {
          name: 'description',
          content: 'DSP CRM defaultd description'
        }
      ],

      script: [
        
    {
      src: 'https://admin.dspcrm.com/wp-content/plugins/mega-main-menu/js/mega-main-menu.js',
      defer: true,
      tagPosition: 'bodyClose'
    },
         {
          src: "https://www.google.com/recaptcha/api.js",
          async: true,
          defer: true
        },
        {
          src: 'https://www.googletagmanager.com/gtag/js?id=G-XWL8VTL6T8',
          async: true
        },
        {
          children: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-XWL8VTL6T8');
          `
        }
      ],
      link: [
        {
          rel: 'icon',
          type: 'image/svg+xml',
          href: 'https://admin.dspcrm.com/wp-content/uploads/2026/02/Fav-icon-dsp.svg'
        },
        {
          rel: 'preload',
          href: '/_nuxt/fa-brands-400.BP5tdqmh.woff2', // Use the exact path/hash generated by Nuxt
          as: 'font',
          type: 'font/woff2',
          crossorigin: 'anonymous'
        }
      ]
    }
  },

  css: [
    '~/assets/css/main.css',
    '@fortawesome/fontawesome-free/css/all.min.css'
  ],

  // ✅ ADD: Vite optimization for better chunking
  vite: {
    build: {
      cssCodeSplit: true,
      rollupOptions: {
        output: {
          manualChunks: {
            'swiper': ['swiper'],
            'aos': ['aos']
          }
        }
      }
    }
  }
})